# Generated by Django 5.1.5 on 2025-01-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aniversario', models.CharField(max_length=15)),
                ('texto', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
